export interface LanguageItem {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const ALL_LANGUAGES: LanguageItem[] = [
  { code: "en", name: "English", nativeName: "English", flag: "/images/flags/za.svg" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "/images/flags/ma.svg" },
  { code: "fr", name: "French", nativeName: "Français", flag: "/images/flags/fr.svg" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "/images/flags/es.svg" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "/images/flags/de.svg" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "/images/flags/it.svg" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "/images/flags/pt.svg" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "/images/flags/ru.svg" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "/images/flags/cn.svg" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "/images/flags/jp.svg" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "/images/flags/kr.svg" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "/images/flags/tr.svg" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "/images/flags/nl.svg" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "/images/flags/in.svg" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "/images/flags/bd.svg" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "/images/flags/in.svg" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "/images/flags/vn.svg" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "/images/flags/pl.svg" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", flag: "/images/flags/ua.svg" },
  { code: "ro", name: "Romanian", nativeName: "Română", flag: "/images/flags/ro.svg" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", flag: "/images/flags/gr.svg" },
  { code: "cs", name: "Czech", nativeName: "Čeština", flag: "/images/flags/cz.svg" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", flag: "/images/flags/hu.svg" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "/images/flags/se.svg" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "/images/flags/id.svg" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", flag: "/images/flags/my.svg" },
  { code: "th", name: "Thai", nativeName: "ไทย", flag: "/images/flags/th.svg" },
  { code: "fa", name: "Persian", nativeName: "فارسی", flag: "/images/flags/ir.svg" },
  { code: "he", name: "Hebrew", nativeName: "עברית", flag: "/images/flags/il.svg" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", flag: "/images/flags/no.svg" },
  { code: "da", name: "Danish", nativeName: "Dansk", flag: "/images/flags/dk.svg" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", flag: "/images/flags/fi.svg" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", flag: "/images/flags/sk.svg" },
  { code: "bg", name: "Bulgarian", nativeName: "Български", flag: "/images/flags/bg.svg" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", flag: "/images/flags/hr.svg" },
  { code: "sr", name: "Serbian", nativeName: "Српски", flag: "/images/flags/rs.svg" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", flag: "/images/flags/lt.svg" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu", flag: "/images/flags/lv.svg" },
  { code: "et", name: "Estonian", nativeName: "Eesti", flag: "/images/flags/ee.svg" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", flag: "/images/flags/si.svg" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge", flag: "/images/flags/ie.svg" },
  { code: "mt", name: "Maltese", nativeName: "Malti", flag: "/images/flags/mt.svg" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska", flag: "/images/flags/is.svg" },
  { code: "al", name: "Albanian", nativeName: "Shqip", flag: "/images/flags/al.svg" },
  { code: "ge", name: "Georgian", nativeName: "ქართული", flag: "/images/flags/ge.svg" },
  { code: "am", name: "Armenian", nativeName: "Հայերեն", flag: "/images/flags/am.svg" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycanca", flag: "/images/flags/az.svg" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақша", flag: "/images/flags/kz.svg" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbekcha", flag: "/images/flags/uz.svg" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog", flag: "/images/flags/ph.svg" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "/images/flags/pk.svg" }
];
