export const products=[
{id:1,name:"Muscle Rub Spray",price:60,cat:"Body Care",color:"#dc2626",sku:"MUSCLE-100",desc:"Pain relief",long:"Arnica menthol eucalyptus"},
{id:2,name:"Chia Seeds 250g",price:40,cat:"Wellness",color:"#16a34a",sku:"CHIA-250",desc:"Superfood omega-3",long:"Organic chia seeds"},
{id:3,name:"Yoni Steaming Herbs",price:60,cat:"Wellness",color:"#92400e",sku:"YONI-50",desc:"Herbal blend 50g",long:"Rose lavender rosemary"},
{id:4,name:"Puso Glow Face Cream",price:80,cat:"Moisturisers",color:"#ec4899",sku:"PUSO-50",desc:"Rosehip vitamin E 50ml",long:"Luxury pink face cream"},
{id:5,name:"Hethagatsa Clear Acne",price:100,cat:"Facial Care",color:"#0891b2",sku:"CLEAR-50",desc:"Target heal prevent",long:"Acne treatment"},
{id:6,name:"Calming Soap Bar",price:40,cat:"Cleansers",color:"#0d9488",sku:"SOAP-100",desc:"Chamomile turmeric 100g",long:"Yellow swirled soap bar"},
{id:7,name:"Kganya Eczema Cream",price:120,cat:"Moisturisers",color:"#15803d",sku:"KGANYA-50",desc:"Oat centella 50g",long:"Eczema soothing"},
{id:8,name:"Vital Gummies",price:150,cat:"Wellness",color:"#db2777",sku:"GUM-60",desc:"60 gummies raspberry",long:"Vitamin A C biotin"},
{id:9,name:"Clear Soap",price:40,cat:"Cleansers",color:"#d6c7b8",sku:"CLEAR-SOAP",desc:"Natural handmade 100g",long:"Beige round soap"},
{id:10,name:"Fofa Scrub",price:80,cat:"Body Care",color:"#a89078",sku:"FOFA-200",desc:"Rose oat 200g",long:"Exfoliating scrub"},
{id:11,name:"Dark Thigh Cream",price:80,cat:"Body Care",color:"#2dd4bf",sku:"THIGH-50",desc:"Brightening 50g",long:"Niacinamide kojic"},
{id:12,name:"Khanya Serum",price:100,cat:"Serums",color:"#fbbf24",sku:"SERUM-30",desc:"Marula baobab 30ml",long:"Gold serum dropper"},
{id:13,name:"Glow Bundle",price:320,cat:"Sets",color:"#d4af37",sku:"BUNDLE",desc:"Serum + scrub set",long:"Complete glow set"},
{id:14,name:"Hydration Boost IV",price:450,cat:"Wellness",color:"#f59e0b",sku:"DRIP-500",desc:"Vitamin C 500mL",long:"Orange IV hydration"},
{id:15,name:"Skincare School",price:1500,cat:"School",color:"#1e3a8a",sku:"SCHOOL",desc:"Certificate course",long:"Learn formulation + business diploma"},
];
